---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: flight-tracker
spec:
  encryptedData:
    DATABASE_URL: AgAMv0H3du2fVYsFoXfZXFMQ+r8Cw2Rf9g3x7McZBHherH+OH/SyV2XWUIX0f9pvDszdNaiyITN4VQeLmvZOGAWNz3HTIfHuA4/P2xoeH4lVZZEdqbYeo7I0IuP+WRYLvCGgVm78A2X5SE91/t3kVBfQV0invOQoW5DpvuzGS4lYnZxqSQQK00sIB1az3NaRV5fVAnzTLH8vdkRMXuc/FQcnn9UMGBsohGjOPWnZ2PGwbiYdpgoULTXYeuiZaAMcYqnmRAI6l5vaeynyoDhWIp1JUbpHfuaotM/Su6cu8oz+EUYG4Y3kTWqIXYfpM+vEAsZUGJCAnul5YmpRwIN3J9tWwhHGXxMHNsESlHjFV1vXsDS5jIfQJWez3VxJqYB9JLDHBu7Mr+gMxOnh0PoE1NBFIcfZ2QoolC8ZOVfPRg37W5wKXCmqW6j+5C5Xq45s/3gCan/PrDqUZGxaWvxnbrApuAObrXpeumAZT/lniFbJmnd1Fo/w4rjED8aFLJykZkmOj1+BNL9ZUNpT7A/AsdzfgEksJH7y3SmCK/fBebjTKbpZlo5htdYkoqwcix6Z588fmRHauaJZxH8irt4xcGijttY97MbDxBwQvcEhS1s5Ilnmelldhh/+idYQS5KBTR2mp2H3hOYM6hMicEAWygRJOoYi8NHffOsQ/TVNU67IdjcmWCYPePLRPybwzd0ievJK32TcPhCgJGN711ztJ9qTkBdcsCeoix26wZciKZfjGHvn9TU918uSH+/NQwbSIBiwcaaYwnCcXVQaq2/QqGWY9DXPv6lhbhcJYB2hKPB1LFpj2w5x
    SECRET_KEY_BASE: AgBAyefHVZRw2xg2oVBpLbFq+j2JZJvHkJOi23VVU/wfuvwqHJlyd9XdwgI408vQrQCfxxKFItsJSGlxwl0WE/DnK7yeymU4qpcm+T7J+6n8lRKX1YoMp8wdFJ6ioCFlnYxPCrOy9AUx3YHJNRY4/TgnGMe18A3dfdEqMlO7dsBJJkNWvnS/UAWQ/eJZMDRrMjkOMoNMMlpLqUwfIW8ceJjdzo2mfoET15mJlCpaPE9INYtyO8nCVEffbRU2ZSAqsSNttwbqqThPgThY0xmdVk3yi/PJZD2Yj7PqwdeZHwCXWFXvxUxfN8KQrTDE4nTLbOH+TzkF7vF+pg2wjb29v98UUEyWYLeyaHJlDWvLYdCsoVE51LhCqw6wpFqbPaw/X2+ZgBqaNmgKMnaKdlQO0IBVcQikua0CHT1nS8MGtLsW0Z9KT1Y55yFASNQGOY8V76bSF6mFHtQG6t4KXnz1gDvN8MP5yATjsQVAFJ8t5TOc1VMtoXp4oBA5f4VWS1RhRrjXCGJChAW1ga5DRnezUEnP/63/hOrKns9Dvhmjy/x3mOiQuf5JMiowRzlZuUVg+fmCsQQlj+fXHC3xDEgLa0X2Q3wVp83zlgs5xpYGUzcjRpXXICuNCAwmbM2cs303ob7iYF85p/OyblYccpOt4q6FC8zgsOPsadJy5dCJ8+Fo7RgJzHZGp0Gf8gpSCMH1AsF9xWZgDeq2LjyGJynH+mU8szJkb6H7sxmkWb4QX6708mC56IJMpGkOOWRbQulwIjIMOuZB8XFsO41Pj08NVDrE6etKO3HVJlfedkNP08x4zCY1ozwBJdMWi1VNPfdqUJnyEOgjb4FSouRtYJgTw6jhQPfKlr+hBqGbrPsAL1jcGA==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: flight-tracker
