---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: flight-tracker
spec:
  encryptedData:
    DATABASE_URL: AgCcenFhHm6PnFEGWcP/iSN4NLLGpbCkjj621GoWMVguzm+1wLZgpwGOntb971odWB7LUj024IjKZ6gLmStKH6CZA9E9dI+P9eXlcpf4cK86FEImLliCgi4RybY6jRd0LuU991PFefY3vbhPduua8997oyZof/IPuUEOMQiUJATzrFajSN4lLNcJMg1FakI9/JmMn1IQA/k/pHA/eXw/E9Ga65IwXTTfrksz6RbUFe6HgYiDX1jUgV11YNefQ6FWRT+3HxX692Z8Itczov+VDpToIw2V4xXNmoA5WJdvP7hrPV6GyaX7X6xhDlfvRRQlPwAwEbay8kUG4qlVn+WWYOgElVkKRR9TWm+gl+lJC9AL7/8yPwYo2/s0NNN6JXjMN93etwwEKMkndBOX9mH8T51ZIbSyjVIeQ5J3Gw27pI/Z9OH7dKClVk6R92kL19lV6DHu/EfGnPXBxcUbOXbV1D8YWi3TANIwGRROdrusu2LZWwC7XaZwwb0HzV1mvodOOTvf1Dq90qzmxnal1bEe+2WcRa1IQbR0x+8I57O+NLCKaIsEKDzt3r0ME8+mZclKRCyhEp1pah3cLdJmR+3q9KUHrGZedBYJZbvPUCqUTPJ1EBg+nFd5UUFoxupZIdEKnazlTA19DzF6nhhX3V73WisJ2+/oQFxLy+izDhOQfkTykYr4YQ+ZjlHP6YTReDtVrbLXbP9D6PfU3yi2Qwsjb5B2QT1UsTUQSmnqrtPhHxH81485eqUKufojNj35s2h+3FlYPCWiZdRfZbiw60m09vZp7cYjAC+OqmNd5p4=
    SECRET_KEY_BASE: AgBI8ceGh+yT+3oRucCXbnlBnX8JVSGbOwh1H/78xdkQFq33Er2lrJeq5Qpy7kSVY/THQGs+96UmUNWtikbyizH8DwrvR15uKdNH2kyPA1srmFAC5AaVvfLTIbQKkCWfKmMLxw0Nrz48NQ4u6iiFB8bZXTz3phKpAEnD77kZWbDdjcVesSnc6Q+9REThRRWnT0baUMcxmkCZtWETW9Feb2srdjc2VcRk2SRnxnOmMVrMSPk5K5d6MvRXIGwn2YUGHjdV6kniJuuhByybTArKFpR5T7I4+fjUHsBIW0QuxjydOn0syXRUTc370SuRui1MrVRcb8HE/PDqlq2h2OoluQ8vrga2ZLo3x4CN4il0I6AKjCdv+5krb+Cu8TMLAvfAVzXp+giTJRq36ALnjZBPmy5thXg+D/lPJ85Ag2rqMWn/mDD28DDzbCis1zt3C/qguugV4xPJjddCiMT0ee10fLHuBFZlfnNWjNbBPoYFxn7VoIAIF9B2wtmm6bANZvJUTjEzSkFqkCPijM0z+vFJB+g3BJPYUnSYVakcpIPdGRRvjdGpe+HiFeoAGaz/+BeyfEm1vhrgur9e20txlBWWJlKgwHGJW/wcym/2TIkxQ83vsnUnv71YOOd6SiqKkuSPdskkFHsrskNmkhfocRIZHWUDExmr7/30uDqr/leUFYtyYY2oEWVzmp/RxejHBhVHxgB9eZQonCyazeJ0J6Go45q61fPiqLQSikC5u+hdlVMoo25T9wgCk7U3z5TmI437nbf+pI9ZvsfrABfxWFLB+PaBelkqdFBE7z3dFZnLlgPcx0oPuGVcMKg+5q4lAo54Xu+0dz/uFcWqYtA56RnHRrDbXJQAeJYmFStlinwC5O5H+A==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: flight-tracker
