---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: flight-tracker
spec:
  encryptedData:
    DATABASE_URL: AgBPwcmMSCDL9HwfuFkz53QM05/lLRJdD5vaMnOxMfij0Y2p3UFK903y1aa5okx2LFlK5765yGbWXYFe5rudOdIYtj16z3hgC/xkM+CcvDTIBAUq7SfzovfHasCJ5mPC/B9/Gu93RTPiQD6BxNvdLbuC5EyS02ma0yhQivYMH0qL9/a7KMWor5gWp1oosjmwhZqU7+lk2euiD4Abg1GO/6RHoye23MYhXPQPmiVySxQGKRaoJTkf0sdYK/HyNbEWjF8jqIb1clVLVpVq7lmn65STOD51FGHV26r8xQy7VWy4g+V8ZC/mhkd/gF6DWFZ1l35BkqJe+Nl6/zb8Znc/46hdILPVlWPvwS6bf+R2SkaRk6i1jD7qTkt8CLAsxG//HbeJdoYVh0xH5E7K6IOBUembVj2PmCBNM71KBWx3Utu684HxX6+UjYYTBN3FKL0NW+L8VaG2DFVQWG1Wa9Pyd5UOm1BF3fKK8NbC9PXCJteM+QhBvusQj/SsNEEdLZv5yW0TgpRZNXfNpGtb8T+7gjAu/kz5LqIkU+CNBgGTU9QpFlE8koC+6fTSP5qEU2p0vJlWHxXqGBAHKpMLAz6vBmsLtM7Js/M4M+6OT3hu+e7osrG02OgXtgjU8mPSEFuSprruifF3kIzSlDMzzYWb1QerD6YHW+Ab8VWTYAPngde1o0V655r7MArBTognWJ63GwjGnvPmURVmp4eYPpE6wJ3rgN4cbYfUyx6AZ2oj98Q4YrplwCMgXuOzO0kb7Rida4xJvHqjixJ/SZN1s5wS1Lsfq0W18LT/finh3XqLSmxTF4kBa8XjDy6k2EzplrE=
    SECRET_KEY_BASE: AgClAlaUYgYMpesMOg9FnaAPrmiEwdANeCTnaOOCww4hyVyzmyyAF1wlIblRQsiiFmjHfM85Fp+GThROgpgHKVPm1Qs6Smf/r+uYioauvHxrlR+TohEVYiPxnauuTJSvnRiBmU1USJPb8i7SqPUtcmMGrvYTSYL+sjQhuNmjvaDoxDmSs5Yrl6kTcAfAPQnaEN3XMVI5Y7GN+MLWwW4pQH2uK1jcmO6N0NXmkZj/CH4dyzBrC/zojoF1Z3YFq7xsElVjdVN8apDhsngOd+qGhOtzR07DN1bOk7eksu751O8dI/zEHHX+6yVs+jDc22IpGQt7fd+DOAM+hYbAYuirzJFlUu3+rvs++oPLyJIDFYI3QWK6EeAYBGMOp/qJE2VlmNp7ZQlCO3pHwUrPg13kURN4dUYjjVaKG8bec6OtZc07Pj3/BjtqgYsfrtReTLFv3aORYBftT8c1R3mZDDcKrHsM7N8z8U2rRm0jUT8AfR0lvYlIsP0RWS9lST6QRxHUIV6UkthmRsoFeMM8Je5gmtJ6R6cUTi3pSydlz+YxpRm2iQZ7xL9J6uhB8A/EhJIN8CBEXubliCy2iBKD51WCovW1yDFXv2JXeibGkg7CeEjRmDVAEQgvyQ1lR3FyhF8w75bcbagaU7FP178hduU4LrRMuTgO8Yo9iHNL+nfBbaWq7aqyJzeGOicNkP/41fT/O6SrtTP4f9cvXjywy2OX5INYtaTIuiWjIaSLOv4IFdL4AunjgdBEVvv2mvIG+diwyrt5Ql08IqUio1iYZaTP/iDgHc8zT+oUCPXodHELlcB9No34TFcfvIkZiyGs+iim+66f92wHxM12dI15koqqvSzXmoAkm0aoD2GxeIcqRk20eQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: flight-tracker
