---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: flight-tracker
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBfKdoSC7t2ej21S+Jnad9ugxWeELJfQxwDgEI95CwcQBuBeO/Nm0GGO+gkJ183qpHv/pRC8D5lIpPcZac1x1qxaCRqinFw7vtK1DEYTsIyBgIAMmnYVlTxIQW6QV5zdjS2QJOy+x0Q2SYVAtaWzbuH898nqsVb0BRtvTqUnMHF5qG2B3p+7Ezd6aQ78ZNARA/6/CymDcy/3OSn+jOJMAQHVGZhXDub3f902LpqkNkmhIXukdvR5UTE2kjBKRMpGr7+OrgwVqmCQM8i8LTuTMvjerqqyF1ZZJN0MKaQK/Py1nGBclqrg02oNKciSMC5KOFFEZgaOPrEHkqBkYnilVEAhsBxP6dCtVWIT1K6MNlYSdk2+QE/4dy+ycTfxYKBgoUwqJYsWRUdftRV9vtQxLyk6b/WsyuC4AEGH/T76zUT+zNmkxeAV8oJmlgnVo+EUK2YdhRD0GnnqJA+ptfBPhZTA74uoZL9CVnE7nav1YZdRfNRO88Ma2SnkAzEn+H+RGH38kdISF2dAz8KPEhUW/C2z2Y3kUcv0ch/AYHdeSwMqOH0+fA2LzQztsDRtsq3YJcZVK8OHnUVRqJ4nJ7R+qT5qs9Yla1KZfIN3aOM7abf6cBU8+DxsHziKMrHCUsItJegjc+HaEBGGk59mj7TjmvqXtpWQHR4qHH5BZkiW/FOUZ9CbIo1VqTV7pWuK8+70jvjGzmtNpFi1zfYFVlnLZvcwCncavMTP7U=
    SECRET_KEY_BASE: AgAM9wNozS1eG1KkhrNVPhdf3iXhVA6IhmDPyeHKfWFxrkbeFLCjSXxWUIFk8bWaDQyEGLnUjo2jr7bLjaV1g8NYxA64UfsG8pWLS2QcJdG4HgqlNT1kHwtwucABea6pW8JWD0e9X1Hxf8X5SiqqsmkW7lhJJcrH2xcf5vqpiYOTQ5Acc3Uoy04NICdSLYj/zpqPU28ecwHJJHXvI1Mwy6+QoGWDv3AEsmIzyGK007Htfi1JAvwI3DiqX4n7YLG9NFTOm4VQsjeGAWo1YAF/tlshwCucAkdOPVWtoVrrAhng5JTeiXOZO9gQKGmxrei4Lkim+ynhUbkISdYQr9OyRztzkJYqNmuyZgBcA0TmWvjkby/j0WVDh8iXLGe3/rE9Jlw2ysxA/jiK46U1EtoAKgeVqDoztyU5gCasb5x0AIR9/Bw0oVykJIivQXA7BxQB6DzAmkgXoKpAZuOwkEt+71VOaFz3U4t3h/eV7AxBA0mSZIlTNZBRn6SfVCia9lvzNnWEhQlc3TXm2TsviHcxsiH160Wgojnk6T4Jk01Z/LmqPilPB4Qaxw6SqSQaHcQVBFGNADmeCU1cw4tgJfQiQXq3U7SpuKFRghfMuCPyyXK2ON9mXVDNHA/b97Yt6/STXJcioXH17bwE7U42o6JJrWXr3J4nDD2CmnVAYMZlAuwbAYT2Dhu6VCO14NohcWN4Bx/BpfLvUyiSzBXLyxryDPxEEnJCCttVhkyy/yUsWcNgF+lJ2eqfadAmulqFydPtjeJ6zNWRXBhnNRNrZih4n32u/enK2kQAJMU0uDZVC1asL7kt9HGdRUQKxOtyhYja184u/7x2oewbKzjFUQ8J8khmQ9OQapeMbaU8/PNulBk1Zw==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: flight-tracker
