---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: flight-tracker
spec:
  encryptedData:
    DATABASE_URL: AgAp2V5YGqh/2+wGWToDhI7CICOJGBNhfIVSzI7PrvrBoNhNhyqGWoEKM3AlevWLKZbQstymDv+SctRow6lqNzZJzJrLdEe6at1PccDkS5nfR7fLlmwmm7iGzwN42ZhAd+G1nLJlKm/3AQ+R70MwsEnYL6rhglmudqZU1ch/2hb1OJMZ9Sdj2OJC+XLqxvux1+4ng6KwJdTc5SxDl7ApKyHL7K2v5ca9c7sQOj6LTt8imKzz9oK72qY5aYbG8Yj1/Pd4TlItYxffPXgtN2kc7z4RENIfmLabNMFjf4d0kab3lO8OyFm7g4SEgigY4cm3KdMiYcU83Y8wxVGAsxoOqop/NN/waV+41ibzfbHuVWN4AAT4kLk4jqsmPM6tULvaMODt283h8lniQa9uLkACA1rV6fuU2jR6qP8Yz5aNNvx2P5BHYfQzCgm4sUqtQdR1aDZzU4XY0DhE4yKSIGY7do1LVasDKDBn3nvTfzoiGm8/ICIX3axpoVTJLmYPuviL8cd0rAb8pbrRlMaL+6BsX/onKJtXRWU5ceL+I8O3gdI9LTKx9UiR1TDcfxOSs47rt5YExvDpCvzwjrbSKZB+PDp+IhPuFaE/yHNvReTfyXEUvWprfrSMNyoLbVI3+MuWawbM87puH8O0XX8dJjNIm952R4gAxhxzRDAc9TVFohtSLQDcQuzPwCQG9B9nIpIx6Dseyh7jI0oOFQvrHiDpzN49p81nocJqERsZqiGwe4jrLNtJ7ahuM9B4ZWOvQfeofEyRq2orH1XzJdeYqnWWyKw60hvyg2Kq7vGROL1nxO0CzBemuQtte7+OYp2ayg==
    SECRET_KEY_BASE: AgAeY5Tj2w64VcLXbnBCWteoTzYwXUYODWALDHVd5Wzw0CBuKFVrzAMDtrZ8pNmfx8Fh38eiwPwphuPlNevVjqa6RJU7aOkjgzydatp1t29xOKX8QQmZ+Q4C5TzWcVcbTu6CV5tBTv7PaCAww2xFAlOd3rc/JlkDhMr8jVTD4+gMgHMMnb4p8Ll/xkv0ezy/VAY1Y7dYrN6zaUjb4R3ehkCpi4kK0N8yV/+cFKeZDmax/bxAhKWP0/0jsohzS00sOKSPwUuNOepZFo6k9gKk+XzQm5BlnxKQ7pubTza2VBaIGCr2zEGGqdDStGXTC+YZS2EFA9ZVDi/W5gX1vV6tBwpWbKL/67qT6kiN6j4/Phwqeh/Pj1gcRltuWCCE8/cFxo7T2hNDqmPj9XzslnySaaw9PbQjbyBA1o8S6H1apaaaXBxhNpUlor3nQyrlS1GJE+0BFbTAmy1SDWfp1v7DTXnySX+sP6oGNEoekux4x7Nrx88btZDonrtKCD0nB03EzCVDztGvLLWtGGB1QkZ0SYTKbOgE5xm35JkWIHSrvCfL+Ae05mDQeErGP41/KWjIjcJu6ADwJeMM6SuAVSEtmPfD2YT6HqbA2nDzRZsVWGj3YZNrIJ9QdUZpHdVnpctvDilCpWea/9BZz9p1davToFWaWH+DkhRs6fvGc7jIW1JN/tbq9mypuGY7tT+EaA2XmgATxwrRytdTtHoXHZomFl1Yer4Vw9VQvt7E7CIrKOSflI2pgjGi7fOEnWwL2/M97Ajv4+eSn/F/hTRRmlImDTyiF5+T8lKdDeOFEz7EKm+0bC4B9E22RY5QQpRxQq9oV4gvLutJKfvRja35+77cJrK79m7st1jHhBDYpg85e0qGnQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: flight-tracker
