---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: flight-tracker
spec:
  encryptedData:
    root-password: AgBHGPVJvMAMi6ynikT1ddPy1J4Vo/YPOp3UXOA7vrF3sOef/pDpt0v4AlT3VMpB/q5xcBS3GYMFzMdL3YALQpS0/l/seEMnxp0eXIb6nkrwWEHeYW7LgZHla2/7pVsat8RAkEFSsV28L1aXVbD9bwDZf88hKF79Z6dkJGfSZuyD38TY6vOkxEjYKjFF/U9GKyQwmY907Khx15aMNWPZNzuGlun0bH+RYw+HweiUYnBxgChQpqne03g98IuFTjrTECuYs7in+Tez/3kkm6nGHPXRiBz3+Vqhvv4Kh16mofzUP9sz8czdAGdSrjtVvROfSCzzilNtIutaAbfM4IxMJbUIz2qoB9+uinID0Qd9Sg+pIXVu5cNIA2nKiouXtJ4VvK68vvWDLgqrX4VsXKk77472TM7o9klC02NqnOsGKT+GFLVlI6mwx2s6h3kGZsJxH07S7nab1GCGBNNiPk3iMczE7dFjg9la7FROntF+akbgrNljtTiw66ceL3Z9NLgT3G/+VgKOJ3MOSfhp15gejrr2bO4yQImdtwAuBXb+v7UXxZjxxzgonsmUNSYvt4zsYb0sx9mikbuheNBTYp7fcMhI+MOhGMgSTtT34DmQDGXxQOMsGGAIPV2zP4MBJ7qev+USoecAP0/2yYhVvPm6sVhdmCuRSXc/buvIuW/AasXGNZmO3NnCcaJP8t7YRQ2diFzHlWZ1PnLyAx7H7QlyrkKbVNs4Te/RTGU=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: flight-tracker
