apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flight-tracker

resources:
  - namespace.yaml
  - mysql.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
  - ingress.yaml
